### ISSUE TITLE
SSL cert exipired

### ISSUE THREAD

**Issue by MECU** [NodeMC/NodeMC-CORE#20]
When navigating to https://docs.nodemc.space/ I get this message in Chrome:

This server could not prove that it is docs.nodemc.space; its security certificate expired 2 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Tuesday, May 24, 2016. Does that look right? If not, you should correct your system's clock and then refresh this page.

You need to update your Let's Encrypt cert. You should setup a cron job to check and update it every week automatically to prevent this in the future.

**Comment by gmemstr** [comment]
Thanks for the report, I did have it to auto-renew but I guess it broke. Will have this fixed shortly. (Also the docs moved to https://NodeMC.space/docs

**Comment by gmemstr** [comment]
Fixed! Thanks for the report.
