### ISSUE TITLE
Forge in NodeMC

### ISSUE THREAD

**Issue by RedstoneGeek223** [NodeMC/NodeMC-CORE#22]
Hey i'm a user of NodeMC and want to use forge how do i do that

**Comment by gmemstr** [comment]
~~After setup, you can move the Forge jar to wherever you specified NodeMC to store jars, rename it to forge.version.jar, and change the confing.json (in the config/ folder) so that the `minecraft` sections looks like this:~~

**Comment by gmemstr** [comment]
Ahem sorry thats the v6 config. For v5 your properties.json should look like this:

``` json
{
  "apikey": "apikey",
  "port": 3000,
  "minecraft_port": 25565,
  "ram": 1024,
  "jar": "forge",
  "version": "version",
  "firstrun": false
}
```

Hope this helps @RedstoneGeek223

**Comment by RedstoneGeek223** [comment]
Thanks for the help! Perhaps update setup screen 5 to reflect this as it says _"Supports up to 1.9, either Spigot or Vanilla."_, or add a help document so people don't get confused as to how to do this like I did

Edit: also is the mod setup the same?
Edit Edit: I did what you said but it still says **"Vanilla Server"** on the client side in the minecraft multiplayer list

**Comment by gmemstr** [comment]
What does your properties.json look like? Also where is your server jarfile located?

**Comment by RedstoneGeek223** [comment]
`{
"apikey": "apikey",
"port": 3000,
"minecraft_port": 25565,
"ram": "2048M",
"jarfile_directory": "/home/username/Minecraft Server/",
"jar": "Forge",
"version": "1.8.9",
"firstrun": false
}`

**Comment by gmemstr** [comment]
What is your jarfile named?

**Comment by RedstoneGeek223** [comment]
"Forge.1.8.9.jar"

**Comment by mdcfe** [comment]
@RedstoneGeek223 Did you use the Forge installer to create a server jar?

**Comment by RedstoneGeek223** [comment]
yes, here is what it was: "minecraft_server.1.8.9.jar"

**Comment by mdcfe** [comment]
I've managed to replicate the issue - it doesn't seem to be a NodeMC bug but I will investigate further.

**Comment by RedstoneGeek223** [comment]
Thanks!

**Comment by mdcfe** [comment]
It looks like the `minecraft_server.1.8.9.jar` isn't actually a Forge jar to me. I'm not sure which jar is the Forge server jar.

**Comment by RedstoneGeek223** [comment]
`minecraft_server.1.8.9.jar` is the jar that forge generates when you install

**Comment by mdcfe** [comment]
Rename the `forge-x.y.z.-a.b.c.d-x.y.z-universal.jar` file to `Forge.1.8.9.jar` (leaving `minecraft_server.x.y.z.jar` alone) and this will start a Forge server. With Forge servers, the `minecraft_server.x.y.z.jar` is only patched when you start the Forge jar.

**Comment by RedstoneGeek223** [comment]
Thanks! ill try this after while doing important things at the moment, and again maybe add a help file to help people with this in the future.

**Comment by mdcfe** [comment]
In later versions of NodeMC, we're planning to overhaul the setup process anyway to support more Minecraft server softwares like SpongeForge, SpongeVanilla, Cauldron and Forge, which will make these easier to use with NodeMC.

**Comment by RedstoneGeek223** [comment]
but until that update comes...?

**Comment by mdcfe** [comment]
@RedstoneGeek223 I'm assuming this worked?

**Comment by RedstoneGeek223** [comment]
Yes it did thanks for the help
