### ISSUE TITLE
Raspberry pi error

### ISSUE THREAD

**Issue by RedstoneGeek223** [NodeMC/NodeMC-CORE#23]
every time i try to run NodeMC i get this error:

```
/home/pi/NodeMC-CORE/Main.js:383
tails.jarfile_directory) || fs.mkdirSync(details.jarfile_directory, 0o777, tru
                                                                    ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

please help!

**Comment by gmemstr** [comment]
I will look into this, thanks for the report!

**Comment by RedstoneGeek223** [comment]
Full Install Log
[Install Log](http://www.mediafire.com/download/uoryegdyshn1jop/Error.txt)

**Comment by mdcfe** [comment]
You seem to be using an old version of Node.js (0.10.29 to be exact). Try installing a newer version with:

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by RedstoneGeek223** [comment]
Works thanks!

**Comment by RedstoneGeek223** [comment]
Threw this error after reboot

```
pi@Pi_MC_Server ~/NodeMC-CORE $ node Main.js
Starting server...
Failed to get the server properties!
Server running at localhost:3000
API Key: 3808e65d80bbe3fe373485c30f5dd830
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:953:11)
    at WriteWrap.afterWrite (net.js:793:14)
```

**Comment by mdcfe** [comment]
Does the Minecraft server start successfully?

**Comment by RedstoneGeek223** [comment]
no it just returns:
**pi@Pi_MC_Server ~/NodeMC-CORE $**

**Comment by danielsteiner** [comment]
That's a problem with the minecraft server and it states that it cant find the server.properties file from minecraft. I had that as well ages ago when the path wasnt correctly set on windows.

**Comment by RedstoneGeek223** [comment]
What about this:
**events.js:160**
**throw er; // Unhandled 'error' event**
**^**

**Error: write EPIPE**
**at exports._errnoException (util.js:953:11)**
**at WriteWrap.afterWrite (net.js:793:14)**

**Comment by RedstoneGeek223** [comment]
Fixed!

**Comment by mdcfe** [comment]
Could you elaborate on how you fixed it?

(Also, please surround your logs by code tags instead of making it all bold.)
