### ISSUE TITLE
Server Start

### ISSUE THREAD

**Issue by deathlynocturnal** [NodeMC/NodeMC-CORE#26]
So currently I have downloaded the repo, and done npm install but when I run it I get the following:

```
/home/minecraft/Panel/NodeMC-CORE/Main.js:383
tails.jarfile_directory) || fs.mkdirSync(details.jarfile_directory, 0o777, tru
                                                                    ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Can you have a look please?

I am running Ubuntu Server 14.04:2

**Comment by gmemstr** [comment]
What version of Node.js are you running?

**Comment by deathlynocturnal** [comment]
V0.10.24

**Comment by deathlynocturnal** [comment]
Okay, so I checked versions turns out apt-get gives me a super old version, so I have updated to V6.2.1

And I followed the instructions on the web and then when I re-run I get this:
Starting server...
Failed to get the server properties!
Server running at localhost:3000
API Key: 3808e65d80bbe3fe373485c30f5dd830
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1007:11)
    at WriteWrap.afterWrite (net.js:793:14)

Also another question, does this not support multiple servers?

**Comment by gmemstr** [comment]
Can you do `touch server.properties` and try again?

Also, no it does not _currently_ support multiple servers, this is something we're looking into for v6/v7 (depending on complexity).

**Comment by deathlynocturnal** [comment]
Ah okay, well I shall check back every now and then until it does.

Thanks anyway.

**Comment by mdcfe** [comment]
You can always host multiple instances with different ports in the config however.

**Comment by jaredallard** [comment]
@md678685 Ubuntu and Debian use really old versions of node ;)

**Comment by mdcfe** [comment]
@jaredallard Not in my experience; maybe 6.0/7.0 and 14.04 have outdated versions of Node.js in their repo? 15.10 and 16.04 have up-to-date versions as far as I know.

**Comment by mdcfe** [comment]
Closing issue.
