### ISSUE TITLE
Trying to start the server throws errors.

### ISSUE THREAD

**Issue by necrogami** [NodeMC/NodeMC-CORE#3]
When i try to start the server i get this: ________________________________________________________________________________
| ~/code/NodeMC-CORE @ Antons-MacBook-Pro (necrogami) 
| => node Main.js 
Generating new API key
/Users/necrogami/code/NodeMC-CORE/Main.js:497
serverSpawnProcess.on('exit', function(code) {
                  ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/necrogami/code/NodeMC-CORE/Main.js:497:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

After which the `server_files/properties.json` file is now empty. I can replace the contents with the contents from github but still when running the `node Main.js` it happens again.

---

| ~/code/NodeMC-CORE @ Antons-MacBook-Pro (necrogami) 
| => npm version
{ nodemc: '1.0.0',
  npm: '3.7.3',
  ares: '1.10.1-DEV',
  http_parser: '2.6.2',
  icu: '56.1',
  modules: '47',
  node: '5.8.0',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

**Comment by gmemstr** [comment]
Alright, this is because I'm not checking if the server has been run before and if it has actually defined the `serverSpawnProcess`. Will be fixed momentarily.

**Comment by gmemstr** [comment]
Fixed as of commit [#55eaa5c](https://github.com/NodeMC/NodeMC-CORE/commit/55eaa5c42ba2023e37cc6b864c5a82fcd829fd3c).
