### ISSUE TITLE
Docs page showing nginx welcom screen

### ISSUE THREAD

**Issue by renejahn** [NodeMC/NodeMC-CORE#33]
There might be a broken/missing nginx server config. When clicking on the link https://docs.nodemc.space/ one just finds the welcome screen of nginx.

**Comment by mdcfe** [comment]
I believe the site currently acknowledges the broken URL?

@gmemstr Any plans to move docs to GH Pages?

**Comment by gmemstr** [comment]
Yes, I do have plans to move them but I've just had no real motivation to do much work on NodeMC since the ES6 rewrite. I'll see what I can do this week.

**Comment by jaredallard** [comment]
We're redoing our docs structure, so this is no longer an issue. See /docs on Github for now.
