### ISSUE TITLE
Error "Failed to get the server properties!" (getServerProps/setport)

### ISSUE THREAD

**Issue by pcdi** [NodeMC/NodeMC-CORE#34]
I think there is an issue in [`getServerProps()`](https://github.com/NodeMC/CORE/blob/master/Main.js#L150-L162).

When it is called  for the first time in [`setport()`](https://github.com/NodeMC/CORE/blob/master/Main.js#L202-L242) ([line 206](https://github.com/NodeMC/CORE/blob/master/Main.js#L206)), because `srvprp` is unitialized and the argument `force` is never used, the following `if` ([l. 151](https://github.com/NodeMC/CORE/blob/master/Main.js#L151)) is always `true`.

``` javascript
if (!force || (typeof srvprp !== "undefined" && srvprp !== null)) 
```

Therefore, `getServerProps()` will just return `srvprp`, which is still uninitialized.

Thus, the `if` in `setport()` ([l. 207](https://github.com/NodeMC/CORE/blob/master/Main.js#L207))

``` javascript
if (props !== null)
```

will yield `false` and subsequently throw the error `"Failed to get the server properties!"` ([l. 225](https://github.com/NodeMC/CORE/blob/master/Main.js#L225)).

The `if` in line 151 should be replaced with

``` javascript
if (!force && !!srvprp)
```

so that it will
- always load `server.properties` if you `force` it to do so, regardless whether or not `srvprp` is defined.
- always load `server.properties` if `srvprp` is not defined.
- return `srvprp` _only_ if it is defined and if you _do not_ `force` it to load `server.properties`.

**Comment by mdcfe** [comment]
Closing as this pertains to v5, which is now deprecated.
