### ISSUE TITLE
ES6: Use async/await

### ISSUE THREAD

**Issue by jaredallard** [NodeMC/NodeMC-CORE#35]
Well, since node 7 pretty much supports this out of the box, why not use `async/await`? This would make the code much more structurally sound and more synchronous like, less callbacks and less `});`

If no issues, I'll probably do this while I'm on a train for 7 hours without internet on Saturday.

/cc @gmemstr @md678685

**Comment by mdcfe** [comment]
See #37 and branch `v6-optimize`.

**Comment by jaredallard** [comment]
See `master` now.
