### ISSUE TITLE
Missing slash in file path

### ISSUE THREAD

**Issue by necrogami** [NodeMC/NodeMC-CORE#5]
Error: Invalid or corrupt jarfile /Users/necrogami/.nodemc/jarfilesvanilla.1.8.9.jar
Error: Invalid or corrupt jarfile /Users/necrogami/.nodemc/jarfilesvanilla.1.8.9.jar

**Comment by gmemstr** [comment]
Closed as of [#1c26400](https://github.com/NodeMC/NodeMC-CORE/commit/1c26400911987ebf3ad4ce2bf12447c17e5ed58b).
