### ISSUE TITLE
[Feature Request] Multi Server Support

### ISSUE THREAD

**Issue by necrogami** [NodeMC/NodeMC-CORE#7]
What is the possibility of adding in functionality to allow one to have multiple servers. While one could spin up an instance for each server you are effectively doubling port usage. <mc and NodeMC>.

**Comment by gmemstr** [comment]
Will consider this, thank you.

**Comment by mdcfe** [comment]
This could be achieved in v5 with plugin magic, although it would still require spinning up another NodeMC instance. In v6, it's likely that this will be much easier to do (either natively or with a plugin).

**Comment by jaredallard** [comment]
This could be a cool idea for seperating servers into daemons. TL;DR: separation of child_process into a daemon. I did something like this in https://github.com/rdelrod/mcfd. It'd also allow servers to stay up if the backend were to ever crash.

Actually, this is probably a good idea to implement to separate the processes.

**Comment by mdcfe** [comment]
Oops, was supposed to be v7.

**Comment by mdcfe** [comment]
@jaredallard We could either fork the process or spawn a completely separate process - the issue being that then we need to be able to handle multiple potentially spammy logs (many plugins love to write to the console multiple times per tick if they feel like it) and also maintain IPC links to each of them.

**Comment by jaredallard** [comment]
Could easily write a wrapper to use socket.io or just webhooks to interact
with a daemon for it.

**Comment by mdcfe** [comment]
@jaredallard We could, but by that point we might as well write a wrapper to tie together multiple NodeMC instances.

**Comment by jaredallard** [comment]
Yeah, it was just a thought.
